name: Build LaTeX documents

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build Winter/310B
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: 'applied stats (2023).tex'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}