name: Build LaTeX documents

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Build notes
        uses: cvxgrp/.github/actions/latex@main
        with:
          paper: applied_stats_2023.tex
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}